name: ad
channels:
  - intel
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0=py_1
  - appnope=0.1.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - click=7.1.2=py_0
  - cloudpickle=1.4.1=py_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h1de35cc_0
  - dask-core=2.17.2=py_0
  - dbus=1.13.14=h517e14e_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dominate=2.4.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=h0a44026_0
  - flask=1.1.2=py_0
  - flask-bootstrap=3.3.7.1=py_0
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.63.1=h70d4741_1
  - icu=58.2=h0a44026_3
  - imageio=2.8.0=py_0
  - importlib-metadata=1.6.0=py37_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2019.4=233
  - intelpython=2020.1=0
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - itsdangerous=1.1.0=py37_0
  - jedi=0.17.0=py37_0
  - jinja2=2.11.2=py_0
  - joblib=0.13.2=py37_1
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py37_0
  - kiwisolver=1.2.0=py37h04f5b5a_0
  - libcxx=10.0.0=1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.3=h0a44026_1
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.1.0=hcb84e12_0
  - llvm-openmp=10.0.0=h28b9765_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h9aa3819_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.1=py37h959d312_0
  - nb_conda=2.2.1=py37_0
  - nb_conda_kernels=2.2.3=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.6=py_0
  - ncurses=6.2=h0a44026_1
  - networkx=2.4=py_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h3304bdc_1
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h0b31af3_0
  - pandas=1.0.3=py37h6c726b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.1.2=py37h4655f20_0
  - pip=20.0.2=py37_3
  - plotly=4.7.1=py_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py37_0
  - pydicom=1.4.2=py_0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.16.0=py37h1de35cc_0
  - python=3.7.7=hf48f09d_4
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py37h1de35cc_0
  - pyyaml=5.3.1=py37h1de35cc_0
  - pyzmq=18.1.1=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.4=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - retrying=1.3.3=py37_2
  - scikit-image=0.16.2=py37h6c726b0_0
  - scikit-learn=0.22.1=py37h27c97d8_0
  - scipy=1.4.1=py37h9fa6033_0
  - seaborn=0.10.1=py_0
  - send2trash=1.5.0=py37_0
  - setuptools=46.4.0=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h5c1f38d_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - traitlets=4.3.3=py37_0
  - vega_datasets=0.8.0=py_0
  - visitor=0.1.3=pyh9f0ad1d_1
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - astunparse==1.6.3
    - base58==2.0.0
    - blinker==1.4
    - boto3==1.13.23
    - botocore==1.16.23
    - cachetools==4.1.0
    - chardet==3.0.4
    - docutils==0.15.2
    - enum-compat==0.0.3
    - gast==0.3.3
    - google-auth==1.15.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.29.0
    - h5py==2.10.0
    - idna==2.9
    - jmespath==0.10.0
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - packaging==20.4
    - pathtools==0.1.2
    - protobuf==3.12.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeck==0.3.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - streamlit==0.61.0
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - toml==0.10.1
    - tornado==5.1.1
    - tzlocal==2.1
    - urllib3==1.25.9
    - validators==0.15.0
    - watchdog==0.10.2
    - wrapt==1.12.1
prefix: /opt/anaconda3/envs/ad
